# Generated by Django 6.1 on 2026-09-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='N° de legajo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta en sistema')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha hasta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='vehiculos.vehiculo', verbose_name='Vehículo')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='encargados.encargado', verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Asignación de vehículo',
                'verbose_name_plural': 'Asignaciones de vehículos',
                'ordering': ['-fecha_desde', '-fecha_registro'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_hasta__isnull', True)), fields=('vehiculo',), name='una_asignacion_activa_por_vehiculo')],
            },
        ),
    ]
