# Generated by Django 6.1 on 2026-09-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encargados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargado',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector'),
        ),
    ]
