# Generated by Django 6.1 on 2026-08-31 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERVICE', 'Service'), ('REPARACION', 'Reparación'), ('CAMBIO_ACEITE', 'Cambio de aceite'), ('REVISION', 'Revisión'), ('NEUMATICOS', 'Neumáticos'), ('ELECTRICO', 'Sistema eléctrico'), ('CHAPA_PINTURA', 'Chapa y pintura'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de mantenimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha de mantenimiento')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso al taller')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida del taller')),
                ('proveedor', models.CharField(blank=True, max_length=150, verbose_name='Proveedor / Taller')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
