# Generated by Django 6.1 on 2026-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=10, unique=True, verbose_name='Dominio (Patente)')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('nro_chasis', models.CharField(max_length=50, verbose_name='N° de chasis')),
                ('nro_motor', models.CharField(max_length=50, verbose_name='N° de motor')),
                ('anio', models.PositiveIntegerField(null=True, verbose_name='Año')),
                ('area_asignada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área asignada')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=30, verbose_name='Estado')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta en sistema')),
            ],
        ),
    ]
